[dependencies]
base = "0.7.3"
motoko-lib = "https://github.com/research-ag/motoko-lib#0.7"
"encoding.mo" = "https://github.com/aviate-labs/encoding.mo#v0.4.1"
"json.mo" = "https://github.com/aviate-labs/json.mo#v0.2.1"